/// Which bundled Han pack leads the fallback chain, and how that is decided.
///
/// This file is pure Dart and imports no Flutter, for the same reason
/// `models.dart` does not: resolution is a pure function of the document's text
/// and its own preference, so it is trivially unit-testable and carries no
/// widget state.
///
/// The detection data itself is **not** here. It lives in
/// `han_script_tables.dart`, which is generated by the same tool run that
/// generates the two font binaries, from their realised cmaps (plan.md §5.4.2).
/// There is deliberately no hand-curated character list anywhere in `lib/`.
library;

import 'han_script_tables.dart';
import 'models.dart';

/// Which bundled Han pack leads the fallback chain.
enum HanScript { hans, hant }

/// A bundled script pack.
///
/// Adding a script means adding one entry here, one asset, one detection set
/// and its tests - not changing the chain shape (plan.md §5.4, §8).
class HanScriptPack {
  const HanScriptPack({
    required this.script,
    required this.family,
    required this.printFamily,
    required this.asset,
  });

  /// The script this pack renders.
  final HanScript script;

  /// The Viewer font family, as declared in `pubspec.yaml`.
  final String family;

  /// The print `@font-face` family. Declared here so the Viewer and print
  /// inventories are the same table rather than two lists that can drift.
  /// The `@font-face` rules that consume it are CP-C.
  final String printFamily;

  /// The repo-relative asset path, matching the `pubspec.yaml` declaration.
  final String asset;
}

/// The bundled packs, in a fixed order. `hans` first is the §5.4.3 default's
/// order and nothing else depends on it.
const List<HanScriptPack> kHanScriptPacks = <HanScriptPack>[
  HanScriptPack(
    script: HanScript.hans,
    family: 'SaudoHans',
    printFamily: 'DF031Hans',
    asset: 'fonts/SaudoHans-Regular.otf',
  ),
  HanScriptPack(
    script: HanScript.hant,
    family: 'SaudoHant',
    printFamily: 'DF031Hant',
    asset: 'fonts/SaudoHant-Regular.otf',
  ),
];

/// The declared default for unresolved ambiguity (plan.md §5.4.3).
///
/// Returned whenever `auto` detection finds no decisive evidence - no exclusive
/// character on either side, or an exact tie - and whenever there is no document
/// at all (the home screen; plan.md §5.5 fact 1).
///
/// This is a **selected constant, not a fall-through**. Both packs sit in every
/// chain, so every code point in the 9,199-code-point shipped union renders
/// whichever pack leads: a wrong default costs regional typographic convention,
/// never readability. The ground for preferring Simplified is asserted, not
/// measured (plan.md §5.4.3, R11/R14).
const HanScript kDefaultHanScript = HanScript.hans;

/// The pack for [script].
HanScriptPack hanScriptPackFor(HanScript script) =>
    kHanScriptPacks.firstWhere((pack) => pack.script == script);

/// Both Han families, the resolved lead first.
///
/// Both are always present, in every chain. That is what makes the default
/// bounded: which one leads changes regional form, never coverage.
List<String> hanFamiliesFor(HanScript lead) => <String>[
  hanScriptPackFor(lead).family,
  for (final pack in kHanScriptPacks)
    if (pack.script != lead) pack.family,
];

/// Whether [codePoint] is in a generated range table.
///
/// Binary search over the flat, ascending, non-overlapping `[lo, hi]` pairs the
/// generator emits. Detection is one linear scan of the source, so this is
/// O(log n) per character and never runs on the scroll or paint path
/// (plan.md §5.6.5).
bool hanScriptTableContains(List<int> table, int codePoint) {
  var low = 0;
  var high = table.length ~/ 2 - 1;
  while (low <= high) {
    final mid = (low + high) >> 1;
    if (codePoint < table[mid * 2]) {
      high = mid - 1;
    } else if (codePoint > table[mid * 2 + 1]) {
      low = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}

/// The exclusive-character votes counted for a source.
///
/// Exposed rather than kept private because the honest limits of the detector
/// (plan.md §5.4.2) are a required, asserted property: an ambiguous document
/// scores zero on both sides, and a Big5 Level 2-heavy Traditional document
/// votes *toward* `hans`. Those are testable facts about this class, not about
/// the enum [resolveHanScript] returns.
class HanScriptEvidence {
  const HanScriptEvidence({required this.hansVotes, required this.hantVotes});

  /// Occurrences - not distinct code points - of Simplified-exclusive characters.
  final int hansVotes;

  /// Occurrences of Traditional-exclusive characters.
  final int hantVotes;

  /// True when the source carries no exclusive character on either side.
  bool get isSilent => hansVotes == 0 && hantVotes == 0;

  /// True when both sides score equally, including silently.
  bool get isTied => hansVotes == hantVotes;

  /// **Strictly** the higher count wins; a tie takes the declared default.
  HanScript get verdict =>
      hantVotes > hansVotes ? HanScript.hant : HanScript.hans;

  /// Counts [source] against the generated exclusive tables.
  factory HanScriptEvidence.of(String source) {
    var hans = 0;
    var hant = 0;
    for (final codePoint in source.runes) {
      if (hanScriptTableContains(kHansExclusiveRanges, codePoint)) {
        hans++;
      } else if (hanScriptTableContains(kHantExclusiveRanges, codePoint)) {
        hant++;
      }
    }
    return HanScriptEvidence(hansVotes: hans, hantVotes: hant);
  }
}

/// Which pack leads for this document.
///
/// [preference] is the document's own rendering preference (plan.md §5.7). An
/// explicit value wins outright and the detector is **not consulted**
/// (§5.4.1); `auto` runs the best-effort detector.
///
/// Detection is best-effort inference, not a guarantee. It cannot resolve a
/// document written only from the 3,715 shared code points, a short one, an
/// exact tie, or a Latin document with a Chinese fragment carrying no exclusive
/// character - and in those cases it returns [kDefaultHanScript] deterministically
/// rather than guessing differently each time (plan.md §5.4.2, §5.4.3).
HanScript resolveHanScript(
  String markdownSource, {
  DocumentScriptPreference preference = DocumentScriptPreference.auto,
}) {
  switch (preference) {
    case DocumentScriptPreference.traditionalChinese:
      return HanScript.hant;
    case DocumentScriptPreference.simplifiedChinese:
      return HanScript.hans;
    case DocumentScriptPreference.auto:
      return HanScriptEvidence.of(markdownSource).verdict;
  }
}

/// The resolved script for a document, or the declared default when there is
/// none - the home screen, where `_document` is null (plan.md §5.5 fact 1).
HanScript resolveHanScriptForDocument(MarkdownDocument? document) {
  if (document == null) return kDefaultHanScript;
  return resolveHanScript(
    document.source,
    preference: document.scriptPreference,
  );
}

/// Whether [source] draws on the shipped Han repertoires at all.
///
/// Drives the reader menu's `Language` tile visibility. Deliberately keyed on
/// the **union** rather than the 3,715-code-point overlap: the overlap rule
/// would hide the control from a document that is unambiguously Chinese but
/// happens to use only pack-exclusive characters, which reads as a bug
/// (plan.md §5.6.4). The accepted residual is R15 - a document whose only Han
/// lies outside both repertoires shows no tile.
bool sourceUsesShippedHan(String source) {
  for (final codePoint in source.runes) {
    if (hanScriptTableContains(kHanUnionRanges, codePoint)) return true;
  }
  return false;
}
